// Earth Star site build.
//
//   node build.mjs            — build HTML/CSS/JS + archive fragments to repo root
//   node build.mjs --images   — additionally regenerate responsive images (slow)
//
// Output layout (committed, served directly by GitHub Pages from the branch root):
//   index.html        — minified, all CSS inlined (one request renders the page)
//   assets/js/main.js — single minified bundle
//   assets/fonts/     — self-hosted variable woff2 subsets
//   assets/img/       — responsive AVIF/WebP hero layers, logo, banner, favicon, og card
//   archive/<id>.html — pre-rendered document fragments, fetched on demand
//
// Filenames are not content-hashed on purpose: GitHub Pages serves everything
// with max-age=600 regardless, so hashing would add churn without cache benefit.

import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { marked } from 'marked';
import { transform } from 'esbuild';
import { cardHTML } from './src/js/card-template.mjs';

const ROOT = new URL('.', import.meta.url).pathname;
const p = (rel) => ROOT + rel;

const manifest = JSON.parse(readFileSync(p('src/archive/manifest.json'), 'utf8'));
const concepts = JSON.parse(readFileSync(p('src/concepts.json'), 'utf8'));

// ── 0. Ideas dashboard: concept tiles rendered at build time (no JS needed to read them) ──

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function ideaHTML(c) {
  const search = [c.name, c.meaning, c.more, c.alignment, c.formula, ...(c.lens || [])].filter(Boolean).join(' ');
  const links = (c.links || []).map((l) => `<a href="${esc(l.href)}">${esc(l.label)}</a>`).join('');
  return `<article class="idea" id="idea-${esc(c.id)}" data-id="${esc(c.id)}" data-lens="${esc((c.lens || []).join(' '))}" data-register="${esc(c.register)}" data-search="${esc(search)}">
  <button class="idea-head" type="button" aria-expanded="false" aria-controls="idea-${esc(c.id)}-more">
    <span class="idea-glyph" aria-hidden="true">${esc(c.glyph)}</span>
    <span class="idea-name">${esc(c.name)}</span>
    <span class="badge" title="${esc(concepts.registers[c.register] || '')}">${esc(c.register)}</span>
  </button>
  <p class="idea-meaning">${esc(c.meaning)}</p>
  <div class="idea-more" id="idea-${esc(c.id)}-more" hidden>
    ${c.formula ? `<p class="idea-formula">${esc(c.formula)}</p>` : ''}
    <p>${esc(c.more)}</p>
    ${c.alignment ? `<p class="idea-align"><strong>For AI:</strong> ${esc(c.alignment)}</p>` : ''}
    ${links ? `<p class="idea-links">${links}</p>` : ''}
  </div>
</article>`;
}

const ideasGrid = concepts.concepts.map(ideaHTML).join('\n');
const ideasLenses = concepts.lenses.map((l) =>
  `<button type="button" class="chip" data-lens="${esc(l.id)}" aria-pressed="${l.id === 'all'}">${esc(l.label)}</button>`).join('');
const registerLegend = Object.entries(concepts.registers).map(([k, v]) =>
  `<span class="legend-item"><span class="badge">${k}</span> ${esc(v)}</span>`).join(' ');

// ── 1. Archive fragments: markdown → HTML, written to /archive ──

mkdirSync(p('archive'), { recursive: true });
marked.setOptions({ mangle: false, headerIds: false });

for (const doc of manifest.docs) {
  const md = readFileSync(p(doc.source), 'utf8')
    .replace(/^---\n[\s\S]*?\n---\n/, ''); // strip YAML frontmatter (skill file)
  const html = marked.parse(md);
  writeFileSync(p(`archive/${doc.id}.html`), html);
  console.log(`archive/${doc.id}.html  ${(html.length / 1024).toFixed(1)}KB`);
}

// ── 2. Client manifest module (no content, just metadata) ──

const clientDocs = manifest.docs.map(({ id, title, category, description, tags, provenance }) =>
  ({ id, title, category, description, tags, provenance }));
writeFileSync(
  p('src/js/manifest.gen.js'),
  '// Generated by build.mjs from src/archive/manifest.json — do not edit.\n' +
  'export const DOCS = ' + JSON.stringify(clientDocs, null, 2) + ';\n'
);

// ── 3. JS bundle ──

mkdirSync(p('assets/js'), { recursive: true });
execFileSync(p('node_modules/.bin/esbuild'), [
  p('src/js/main.js'),
  '--bundle', '--minify', '--format=iife',
  '--target=es2020',
  '--outfile=' + p('assets/js/main.js')
], { stdio: 'inherit' });

// ── 4. Fonts ──

mkdirSync(p('assets/fonts'), { recursive: true });
for (const f of ['CormorantGaramond.woff2', 'CormorantGaramond-italic.woff2', 'DMSans.woff2']) {
  cpSync(p('src/fonts/' + f), p('assets/fonts/' + f));
}

// ── 5. HTML: inline minified CSS, pre-render archive grid, light minify ──

const fontsCss = readFileSync(p('src/fonts/fonts.css'), 'utf8');
const siteCss = readFileSync(p('src/css/site.css'), 'utf8');
const { code: minCss } = await transform(fontsCss + siteCss, { loader: 'css', minify: true });

let html = readFileSync(p('src/index.html'), 'utf8');
html = html.replace('<!--BUILD:CSS-->', '<style>' + minCss + '</style>');
html = html.replace('<!--BUILD:ARCHIVE_GRID-->', manifest.docs.map(cardHTML).join('\n'));
html = html.replace('<!--BUILD:IDEAS_GRID-->', ideasGrid);
html = html.replace('<!--BUILD:IDEAS_LENSES-->', ideasLenses);
html = html.replace('<!--BUILD:REGISTER_LEGEND-->', registerLegend);

// Mock fixture for ?mock=1 and tests — never consulted by the live path
mkdirSync(p('assets/data'), { recursive: true });
cpSync(p('src/data/now.mock.json'), p('assets/data/now.mock.json'));

// Conservative HTML minify: strip comments and leading indentation only —
// never touches intra-line whitespace, so inline elements are safe.
html = html
  .replace(/<!--(?!\[)[\s\S]*?-->/g, '')
  .split('\n').map(l => l.trimEnd()).filter(l => l.trim() !== '').map(l => l.replace(/^\s+/, '')).join('\n');

writeFileSync(p('index.html'), html);
console.log(`index.html  ${(html.length / 1024).toFixed(1)}KB (css inlined)`);

// ── 6. Images (only with --images: slow, output is committed) ──

if (process.argv.includes('--images')) {
  const sharp = (await import('sharp')).default;
  const IMG = p('assets/img');
  rmSync(IMG, { recursive: true, force: true });
  mkdirSync(IMG, { recursive: true });

  const layers = [
    { src: 'Assets/0-BG.png', name: '0-BG', widths: [640, 960, 1280], avifQuality: 45 },
    { src: 'Assets/1-earth.png', name: '1-earth', widths: [960, 1440, 2048] },
    { src: 'Assets/2-sun.png', name: '2-sun', widths: [960, 1440, 2048] },
    { src: 'Assets/3-islandship.png', name: '3-islandship', widths: [960, 1440, 2048] },
    { src: 'Assets/4-glimmer.png', name: '4-glimmer', widths: [960, 1440, 2048] }
  ];

  for (const { src, name, widths, avifQuality } of layers) {
    for (const w of widths) {
      const base = sharp(p(src)).resize({ width: w });
      await base.clone().avif({ quality: avifQuality ?? 55, effort: 6 }).toFile(`${IMG}/${name}-${w}.avif`);
      await base.clone().webp({ quality: 78 }).toFile(`${IMG}/${name}-${w}.webp`);
      console.log(`${name}-${w} avif+webp`);
    }
  }

  await sharp(p('Assets/EarthStar Logo JH 2025 w.png')).resize({ width: 480 })
    .webp({ quality: 88 }).toFile(`${IMG}/logo-480.webp`);

  const banner = sharp(p('Assets/EarthstarBanner.PNG')).resize({ width: 1200 });
  await banner.clone().avif({ quality: 60, effort: 6 }).toFile(`${IMG}/banner-1200.avif`);
  await banner.clone().webp({ quality: 80 }).toFile(`${IMG}/banner-1200.webp`);

  // OG card: banner centered on the site's night ground (dark green), 1200×630
  const bannerBuf = await sharp(p('Assets/EarthstarBanner.PNG')).resize({ width: 1140 }).png().toBuffer();
  const bh = (await sharp(bannerBuf).metadata()).height;
  await sharp({ create: { width: 1200, height: 630, channels: 3, background: '#0e2117' } })
    .composite([{ input: bannerBuf, left: 30, top: Math.round((630 - bh) / 2) }])
    .jpeg({ quality: 86 }).toFile(`${IMG}/og.jpg`);

  // Favicon: gold four-point star on the site's night ground
  writeFileSync(`${IMG}/favicon.svg`,
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">` +
    `<rect width="64" height="64" rx="14" fill="#0e2117"/>` +
    `<path d="M32 8 L37 27 L56 32 L37 37 L32 56 L27 37 L8 32 L27 27 Z" fill="#e9b92c"/>` +
    `<circle cx="32" cy="32" r="3.4" fill="#0e2117"/>` +
    `</svg>`);

  console.log('images done');
}

console.log('build complete');
