/**
 * The T89c port, against the Python `geopack` package.
 *
 * There is no other way to trust a two-hundred-line translation of a
 * closed-form empirical fit. Every intermediate in it is meaningless on its
 * own — `ak812`, `eszy2`, `f9` — so no amount of reading catches a transposed
 * sign, and a wrong version still draws a magnetosphere-shaped magnetosphere.
 * The reference grid spans the regions where different current systems
 * dominate, because a port can be right in one and wrong in another.
 *
 * Reference generated by `scripts/gen-t89-reference.py` from
 * geopack (github.com/tsssss/geopack), an independent Python translation of
 * the same Fortran.
 */

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { Vector3 } from 'three';
import {
  T89_BAND_COUNT, T89_SUNWARD_LIMIT_RE, T89_VALID_RE,
  kpBandFraction, kpBandIndex, t89Citation, t89Vector,
} from '../src/models/t89.js';
import { T89_PARAM, T89_PARAM_COUNT } from '../src/models/t89-coeffs.js';
import { parseT89 } from '../scripts/gen-t89.mjs';

type Row = [string, number, number, number, number, number, number, number, number];
const REF: { rows: Row[] } = JSON.parse(
  readFileSync(new URL('./fixtures/t89-geopack.json', import.meta.url), 'utf8'),
);

describe('T89c vs the geopack reference implementation', () => {
  /**
   * The measured worst deviation over all 1540 rows is 4.3 × 10⁻¹⁴ nT — pure
   * floating-point round-off, since the two implementations evaluate the same
   * closed form in the same order in the same double precision. There is no
   * model difference to allow for at all.
   *
   * The assertion is set eight orders of magnitude looser than that, at a
   * millionth of a nanotesla, purely so a one-ULP difference in a platform's
   * `exp` cannot fail the suite. It is still eight orders tighter than
   * anything that could matter: a real transcription error — a wrong sign, a
   * swapped coefficient, a dropped tilt term — moves the field by a substantial
   * fraction of itself, which is tens of nT here, not billionths.
   */
  const TOL_NT = 1e-6;

  it(`agrees on all ${REF.rows.length} reference points to ${TOL_NT} nT`, () => {
    const out = new Vector3();
    let worst = 0;
    let worstAt = '';
    for (const [name, iopt, tilt, x, y, z, bx, by, bz] of REF.rows) {
      const v = t89Vector(new Vector3(x, y, z), iopt - 1, tilt, out);
      expect(v, `${name} is inside the model's validity radius`).not.toBeNull();
      for (const [ours, ref, axis] of [
        [v!.x, bx, 'Bx'], [v!.y, by, 'By'], [v!.z, bz, 'Bz'],
      ] as [number, number, string][]) {
        const err = Math.abs(ours - ref);
        if (err > worst) {
          worst = err;
          worstAt = `${name} (Kp band ${iopt}, tilt ${tilt}) ${axis}: `
            + `ours ${ours} vs ${ref}`;
        }
      }
    }
    expect(worst, `worst deviation ${worst.toExponential(2)} nT at ${worstAt}`)
      .toBeLessThan(TOL_NT);
  });

  it('covers every band and every region of the reference grid', () => {
    // A tolerance test passes trivially if the fixture is empty or narrow, so
    // assert the grid is the one the brief asked for rather than trusting it.
    const bands = new Set(REF.rows.map((r) => r[1]));
    const tilts = new Set(REF.rows.map((r) => r[2]));
    const names = new Set(REF.rows.map((r) => r[0]));
    expect(bands.size).toBe(T89_BAND_COUNT);
    expect(tilts.size).toBeGreaterThanOrEqual(5);
    expect(names.size).toBeGreaterThanOrEqual(40);
    // Dayside, tail, lobes and the inner region all present.
    const xs = REF.rows.map((r) => r[3]);
    expect(Math.max(...xs)).toBeGreaterThanOrEqual(12);
    expect(Math.min(...xs)).toBeLessThanOrEqual(-60);
    expect(Math.max(...REF.rows.map((r) => Math.abs(r[5])))).toBeGreaterThanOrEqual(12);
    // And a tilt of exactly zero, where every `sps` term drops out — the case
    // a sign error in the tilt handling would sail straight through.
    expect(tilts.has(0)).toBe(true);
  });
});

describe('coefficients', () => {
  it('the generated module still matches the vendored Fortran', () => {
    // Drift guard, same as IGRF's: vendor/t89c.f is the source of truth and
    // src/models/t89-coeffs.ts is generated from it.
    const text = readFileSync(new URL('../vendor/t89c.f', import.meta.url), 'utf8');
    const parsed = parseT89(text);
    expect(parsed.length).toBe(T89_BAND_COUNT);
    for (let b = 0; b < T89_BAND_COUNT; b++) {
      expect(T89_PARAM[b]!.length).toBe(T89_PARAM_COUNT);
      for (let i = 0; i < T89_PARAM_COUNT; i++) {
        expect(T89_PARAM[b]![i], `band ${b + 1}, parameter ${i + 1}`).toBe(parsed[b]![i]);
      }
    }
  });

  it('carries the parameters the paper fixes across every band', () => {
    // A(26) Delta = 0.01, A(27) Q = 0, A(29) Gam = 4, A(30) Dyc = 20 were held
    // fixed in the published fit. If the column-major unpacking of PARAM(30,7)
    // were transposed, these would land in different slots and stop being
    // constant — which is precisely how a silent reshape error announces itself.
    for (let b = 0; b < T89_BAND_COUNT; b++) {
      expect(T89_PARAM[b]![25], `Delta, band ${b + 1}`).toBe(0.01);
      expect(T89_PARAM[b]![26], `Q, band ${b + 1}`).toBe(0);
      expect(T89_PARAM[b]![28], `Gam, band ${b + 1}`).toBe(4);
      expect(T89_PARAM[b]![29], `Dyc, band ${b + 1}`).toBe(20);
    }
  });
});

describe('Kp bands', () => {
  it('maps Kp onto the seven bands the source documents', () => {
    // IOPT 1..7 ↔ Kp 0/0+, 1−/1/1+, ... , ≥6−. Bands are on integer Kp, so
    // 2+ (Kp 2.7) is still band 3, not band 4.
    expect(kpBandIndex(0)).toBe(0);
    expect(kpBandIndex(0.33)).toBe(0);
    expect(kpBandIndex(1)).toBe(1);
    expect(kpBandIndex(2.7)).toBe(2);
    expect(kpBandIndex(3)).toBe(3);
    expect(kpBandIndex(5.67)).toBe(5);
    expect(kpBandIndex(6)).toBe(6);
    expect(kpBandIndex(9)).toBe(6);
  });

  it('returns nothing rather than "quiet" when Kp is unknown', () => {
    // Band 1 is the quiet fit. Falling back to it for a missing Kp would draw
    // a confident, reassuring magnetosphere out of no measurement at all.
    expect(kpBandIndex(Number.NaN)).toBeNull();
    expect(kpBandIndex(Infinity)).toBeNull();
    // Real but out-of-range values do clamp: Kp is defined on 0–9.
    expect(kpBandIndex(-1)).toBe(0);
    expect(kpBandIndex(12)).toBe(T89_BAND_COUNT - 1);
  });

  it('reports where inside a band a Kp value sits', () => {
    expect(kpBandFraction(3)).toBeCloseTo(0, 12);
    expect(kpBandFraction(3.33)).toBeCloseTo(0.33, 12);
    expect(kpBandFraction(3.67)).toBeCloseTo(0.67, 12);
    // The top band is open-ended, so "how far through it" has no meaning;
    // saying mid-band is the honest answer, not zero.
    expect(kpBandFraction(8)).toBe(0.5);
    expect(kpBandFraction(Number.NaN)).toBe(0.5);
  });
});

describe('validity', () => {
  it('refuses to evaluate beyond the 70 Rₑ fit region', () => {
    // Returning zero there would be worse than refusing: the caller would get
    // IGRF alone and draw a tidy dipole in a region where the real field is
    // nothing of the kind.
    expect(t89Vector(new Vector3(0, 0, T89_VALID_RE - 0.1), 0, 0)).not.toBeNull();
    expect(t89Vector(new Vector3(0, 0, T89_VALID_RE + 0.1), 0, 0)).toBeNull();
    expect(t89Vector(new Vector3(-71, 0, 0), 3, 0.2)).toBeNull();
    expect(t89Vector(new Vector3(-40, -40, -40), 3, 0.2)).not.toBeNull();  // r ≈ 69.3
    expect(t89Vector(new Vector3(-41, -41, -41), 3, 0.2)).toBeNull();      // r ≈ 71.0
  });

  it('refuses the dayside beyond the boundary it does not model', () => {
    // T89 has no magnetopause. Its Chapman–Ferraro term keeps growing outside
    // one, so evaluated far sunward it returns a large, confident, meaningless
    // field — and one cusp field line at Kp ≥ 6 followed it to 69 Rₑ before
    // this guard existed.
    expect(t89Vector(new Vector3(T89_SUNWARD_LIMIT_RE - 0.1, 0, 0), 6, 0)).not.toBeNull();
    expect(t89Vector(new Vector3(T89_SUNWARD_LIMIT_RE + 0.1, 0, 0), 6, 0)).toBeNull();
    // The limit is sunward only. The tail is where the model has most to say,
    // and it runs to the fit sphere.
    expect(t89Vector(new Vector3(-60, 0, 0), 6, 0)).not.toBeNull();
  });

  it('leaves room between the limit and anything physical', () => {
    // The guard must not clip the magnetosphere it is protecting. T89's own
    // last closed field line reaches 10.7 Rₑ at its quietest; the Shue nose
    // reaches ~14.5 Rₑ under the thinnest wind on record.
    expect(T89_SUNWARD_LIMIT_RE).toBeGreaterThan(15);
  });

  it('says what the model does not include', () => {
    expect(t89Citation()).toMatch(/Tsyganenko 1989/);
    expect(t89Citation()).toMatch(/no IMF/i);
  });
});

/**
 * Behaviour a wrong-but-self-consistent port would not reproduce. The reference
 * table above is the real check; these say *what the numbers mean*, so a future
 * change that quietly swaps an axis or a sign fails with a sentence rather than
 * with a row number.
 */
describe('the physics the external field is there to add', () => {
  const at = (x: number, y: number, z: number, band: number, tilt = 0) =>
    t89Vector(new Vector3(x, y, z), band, tilt)!;

  it('reverses the tail field across the neutral sheet, sunward in the north lobe', () => {
    // The cross-tail current sheet is the largest single deformation IGRF is
    // missing. Its signature: Bx points toward the Earth above the sheet and
    // away below it, vanishing on it.
    for (const band of [0, 3, 6]) {
      expect(Math.abs(at(-20, 0, 0, band).x), `sheet, band ${band + 1}`).toBeLessThan(1e-9);
      for (const z of [1, 5, 10]) {
        const north = at(-20, 0, z, band);
        const south = at(-20, 0, -z, band);
        expect(north.x, `north lobe z=${z}, band ${band + 1}`).toBeGreaterThan(0);
        expect(south.x, `south lobe z=${z}, band ${band + 1}`).toBeLessThan(0);
        // At zero tilt the two lobes are mirror images.
        expect(north.x + south.x).toBeCloseTo(0, 9);
      }
    }
  });

  it('inflates the inner magnetosphere as Kp rises — the ring current', () => {
    // This is the deformation Dst measures, and the reason the brief called
    // out that we display Dst beside a field that could not respond to it.
    // Southward (negative Bz) at the ring current's peak, growing every band.
    let previous = 0;
    for (let band = 0; band < T89_BAND_COUNT; band++) {
      const bz = at(4, 0, 0, band).z;
      expect(bz, `band ${band + 1} depresses the field`).toBeLessThan(0);
      expect(Math.abs(bz), `band ${band + 1} vs ${band}`).toBeGreaterThan(previous);
      previous = Math.abs(bz);
    }
    // The full swing is large: quiet to storm more than sextuples it.
    expect(Math.abs(at(4, 0, 0, 6).z) / Math.abs(at(4, 0, 0, 0).z)).toBeGreaterThan(6);
  });

  it('compresses the dayside — the Chapman–Ferraro currents', () => {
    // Outside a few Rₑ the CF field on the Sun–Earth line is northward, which
    // opposes the dipole's southward equatorial field and eventually cancels
    // it: that cancellation is the magnetopause, and it is why deleting the
    // geometric clamp works at all. It must grow with distance.
    let previous = -Infinity;
    for (const x of [8, 10, 12, 15, 20]) {
      const bz = at(x, 0, 0, 2).z;
      expect(bz, `x=${x}`).toBeGreaterThan(0);
      expect(bz, `x=${x} vs the point inside it`).toBeGreaterThan(previous);
      previous = bz;
    }
  });

  it('warps the tail current sheet with the dipole tilt', () => {
    // Zero tilt puts the sheet on the GSM equator; a tilted dipole lifts it
    // away from the equator down-tail, and reversing the tilt mirrors it. If
    // the tilt were being ignored, all three of these would be equal.
    const flat = at(-20, 0, 0, 3, 0).x;
    const leaning = at(-20, 0, 0, 3, 0.5).x;
    const away = at(-20, 0, 0, 3, -0.5).x;
    expect(Math.abs(flat)).toBeLessThan(1e-9);
    expect(Math.abs(leaning)).toBeGreaterThan(1);
    expect(leaning + away).toBeCloseTo(0, 6);
  });

  it('is duskward-symmetric at zero tilt, which is the frame working', () => {
    // T89 has no IMF By, so nothing breaks the dawn–dusk symmetry. Bx and Bz
    // must be even in y and By odd. A transposed axis in the port would show
    // up here and nowhere in the tolerance test's headline number.
    for (const [x, z] of [[-15, 4], [6, 0], [-30, -6]] as [number, number][]) {
      const dusk = at(x, 8, z, 4);
      const dawn = at(x, -8, z, 4);
      expect(dusk.x).toBeCloseTo(dawn.x, 9);
      expect(dusk.z).toBeCloseTo(dawn.z, 9);
      expect(dusk.y).toBeCloseTo(-dawn.y, 9);
    }
  });
});
