// Generated by build.mjs from src/archive/manifest.json — do not edit.
export const DOCS = [
  {
    "id": "wrf",
    "title": "Waste Reclamation Fund",
    "category": "POLICY",
    "description": "Legislative proposal: the WRF mechanism, funding structure, and implementation path.",
    "tags": [
      "policy",
      "wrf",
      "economics"
    ],
    "provenance": {
      "status": "Proposed legislation — draft text, not enacted law",
      "author": "Earth Star / JHDesign",
      "date": "2025"
    }
  },
  {
    "id": "harmonious-computing",
    "title": "Harmonious Computing Act",
    "category": "POLICY",
    "description": "Model legislation treating datacenters as organs of living infrastructure — sited, powered, cooled, and integrated as mutualistic participants in urban and rural ecosystems.",
    "tags": [
      "policy",
      "datacenter",
      "computing",
      "ecology"
    ],
    "provenance": {
      "status": "Model legislation — draft text, not enacted law",
      "author": "Earth Star / JHDesign",
      "date": "2025"
    }
  },
  {
    "id": "earth-star-skill",
    "title": "Earth Star Framework",
    "category": "FRAMEWORK",
    "description": "The complete operational specification — Gomens, Earth Stewards, five scales, kincentric worldview, seed equations, and the v3.0 epistemic-integrity protocols.",
    "tags": [
      "framework",
      "gomens",
      "spec"
    ],
    "provenance": {
      "status": "Framework specification — vision & design document",
      "author": "Earth Star / JHDesign",
      "date": "2025–2026 · v3.0"
    }
  }
];
